OldMongoDB:
  image: mongo:3.2
  ports:
    - "27015:27017"
  volumes:
    - ./data/mongodb/3.2:/var/lib/mongodb

NewMongoDB:
  image: mongo:4.2
  ports:
    - "27016:27017"
  volumes:
    - ./data/mongodb/4.2:/var/lib/mongodb
